I"Ğ<p>Gáº§n Ä‘Ã¢y mÃ¬nh cÃ³ lÃ m má»™t dá»± Ã¡n chuyá»ƒn Ä‘á»‘i tÆ°á»£ng tá»« Cad qua Revit vÃ  gáº·p má»™t sÃ³ khÃ³ khÄƒn. khi báº¡n viáº¿t Revit Addin Ä‘Ã´i khi cÃ³ nhá»¯ng dá»¯ liá»‡u báº¡n muá»‘n nháº­n tá»« Autocad Ä‘á»ƒ xá»­ lÃ½ cho Addin cá»§a mÃ¬nh. ThÃ´ng thÆ°á»ng ta cÃ³ thá»ƒ viáº¿t má»™t Addin phá»¥ trong Cad Ä‘á»ƒ xuáº¥t thÃ´ng tin ra file Ä‘á»ƒ Ä‘á»c trong Revit. NhÆ°ng Autodesk cÃ²n há»— trá»£ cho chÃºng ta má»™t bá»™ API ráº¥t há»¯u Ã­ch Ä‘á»ƒ tÆ°Æ¡ng tÃ¡c trá»±c tiáº¿p vá»›i Autocad tá»« mÃ´i trÆ°á»ng bÃªn ngoÃ i lÃ  <strong>Autocad Interop</strong> sá»­ dá»¥ng Active X. Active X cho phÃ©p báº¡n tÆ°Æ¡ng tÃ¡c vá»›i cáº£ mÃ´i trÆ°á»ng bÃªn trong vÃ  bÃªn ngoÃ i Autocad. DÆ°á»›i Ä‘Ã¢y lÃ  má»™t sá»‘ code máº«u mÃ¬nh tÃ¬m hiá»ƒu Ä‘Æ°á»£c, cháº¡y trong mÃ´i trÆ°á»ng Revit, viáº¿t báº±ng c#.</p>
<h2 id="káº¿t-ná»‘i-vá»›i-autocad-vÃ -láº¥y-vá»-active-document">Káº¿t ná»‘i vá»›i Autocad vÃ  láº¥y vá» Active Document</h2>
<p>Äá»ƒ sá»­ dá»¥ng báº¡n pháº£i add hai thÆ° viá»‡n lÃ  <strong>Autodesk.AutoCAD.Interop</strong> vÃ  <strong>Autodesk.AutoCAD.Interop.Common</strong> náº±m trong thÆ° má»¥c <strong>C:\Program Files\Autodesk\yourcadversion</strong>.</p>
<div class="language-bash highlighter-rouge"><div class="highlight"><pre class="highlight"><code>AcadApplication App <span class="o">=</span> <span class="o">(</span>AcadApplication<span class="o">)</span>Marshal.GetActiveObject<span class="o">(</span>AutoCAD.Application<span class="o">)</span><span class="p">;</span>
AcadDocument thisDrawing <span class="o">=</span> App.ActiveDocument<span class="p">;</span>
Message.Show<span class="o">(</span>thisDrawing.FullName<span class="o">)</span><span class="p">;</span>
</code></pre></div></div>
<p>Äoáº¡n mÃ£ trÃªn sá»­ dá»¥ng lá»›p Marshal Ä‘á»ƒ láº¥y vá» Instance cá»§a chÆ°Æ¡ng trÃ¬nh Cad Ä‘ang cháº¡y. HÃ£y lÆ°u Ã½ lÃ  Ä‘ang cháº¡y nhÃ©, vÃ¬ náº¿n khÃ´ng sáº½ gÃ¢y ra lá»—i. Sau Ä‘Ã³ ta láº¥y vá» documnet Ä‘ang má»Ÿ vÃ  in ra tÃªn Ä‘áº§y Ä‘á»§ cá»§a documnet Ä‘Ã³. báº¡n cÅ©ng cÃ³ thá»ƒ má»Ÿ documnet báº±ng lá»‡nh <strong>App.Documents.Open(path);</strong>. DÆ°á»›i Ä‘Ã¢y lÃ  sÆ¡ Ä‘á»“ tá»•ng quang cá»§a Cad Api.
<img src="/assets/img/how-to-start-activex/sodo.png" alt="img1" /></p>
<h2 id="thao-tÃ¡c-vá»›i-document">Thao tÃ¡c vá»›i Document</h2>
<h3 id="láº¥y-vá»-táº¥t-cáº£-entity">Láº¥y vá» táº¥t cáº£ Entity</h3>
<div class="language-bash highlighter-rouge"><div class="highlight"><pre class="highlight"><code>AcadApplication App <span class="o">=</span> <span class="o">(</span>AcadApplication<span class="o">)</span>Marshal.GetActiveObject<span class="o">(</span>ProgId<span class="o">)</span><span class="p">;</span>
AcadDocument thisDrawing <span class="o">=</span> App.ActiveDocument<span class="p">;</span>
AcadModelSpace modelSpace <span class="o">=</span> thisDrawing.ModelSpace<span class="p">;</span>
<span class="k">for</span> <span class="o">(</span>int i <span class="o">=</span> 0<span class="p">;</span> i &lt; modelSpace.Count<span class="p">;</span> i++<span class="o">)</span>
<span class="o">{</span>
    AcadEntity item <span class="o">=</span> modelSpace.Item<span class="o">(</span>i<span class="o">)</span><span class="p">;</span>
                
<span class="o">}</span>
</code></pre></div></div>
<h3 id="láº¥y-center-point-cá»§a-text">Láº¥y center point cá»§a text</h3>
<p>``` bash
private void GetText(AcadEntity item)
{
    if (item is AcadText text)
    {
        object cMaxP;
        object cMinP;
        text.GetBoundingBox(out cMinP, out cMaxP);</p>
:ET